name: news_app_clean_architecture
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #make request to api
  http: ^1.1.0

  uuid: ^4.1.0

  #state management
  flutter_bloc: ^8.0.1

  #comparing dart objects
  equatable: ^2.0.3
  
  #service locator
  get_it: ^7.2.0

  #chaced image
  cached_network_image: ^3.2.0

  #show toast
  fluttertoast: ^8.0.9

 #Hooks
  flutter_hooks: ^0.20.2

  #Database
  floor: ^1.4.2

  shortid: ^0.1.2



  #Bottom sheet
  modal_bottom_sheet: ^2.0.1

  #icon
  ionicons: ^0.2.2

  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
 